# Artificial Neural Network

### Importing the libraries

In [88]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [90]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [94]:
dataset = pd.read_excel('../Dataset/Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [95]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [97]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size = 0.2, random_state= 0)

## Part 2 - Building the ANN

In [102]:
ann = tf.keras.models.Sequential()

### Initializing the ANN

### Adding the input layer and the first hidden layer

In [106]:
ann.add(tf.keras.layers.Dense(units=28, activation='relu'))

### Adding the second hidden layer

In [109]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [112]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [116]:
ann.compile(optimizer = 'adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [119]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 969us/step - loss: 17798.3027
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 426.2321  
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 307.0222
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 835us/step - loss: 224.9622
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 151.5359
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 785us/step - loss: 101.4011
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 851us/step - loss: 66.7363
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 854us/step - loss: 51.0115
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 840us/step - loss: 42.7506
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 842us/step - loss: 37.1139
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 871us/step - loss: 32.9139
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - loss: 29.7070
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 957us/step - loss: 28.7610
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - loss: 28.65

### Predicting the results of the Test set

In [131]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[433.44 431.23]
 [462.14 460.01]
 [468.34 461.14]
 ...
 [474.94 473.26]
 [440.96 438.  ]
 [459.37 463.28]]
